import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import ListAnime from '../features/anime/ListAnime'
// import ListCollection from '../features/collection/ListCollection'
import AppLayout from '../layouts/AppLayout'

const ListCollection = dynamic(
  () => import('../features/collection/ListCollection' as any),
  {
    ssr: false,
  }
)

const Collection: NextPage = () => {
  return (
    <AppLayout>
      <Head>
        <title>Collection List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListCollection />
    </AppLayout>
  )
}

export default Collection
