import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ListAnime from '../features/anime/ListAnime'
import AppLayout from '../layouts/AppLayout'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <AppLayout>
      <Head>
        <title>Anime List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListAnime />
    </AppLayout>
  )
}

export default Home
