import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import MyPortofolio from '../components/MyPortfofolio'
import AppLayout from '../layouts/AppLayout'
import SiteLayout from '../layouts/SiteLayout'


const Portofolio: NextPage = () => {
    return (
        <SiteLayout>
            <Head>
                <title>My Portofolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <h3>My Latest Project</h3>
                <div style={{padding:'20px 0 20px 0'}}>
                    <MyPortofolio />
                </div>
            </div>
        </SiteLayout>
    )
}

export default Portofolio
