import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
// import DetailAnime from '../../features/anime/DetailAnime'
import AppLayout from '../../layouts/AppLayout'

const DetailAnime : any = dynamic(
    () => import('../../features/anime/DetailAnime' as any),
    {
        ssr: false,
    }
)

const Home: NextPage = () => {
    const router = useRouter();
    const { id } = router.query;
    return (
        <AppLayout>
            <Head>
                <title>Anime Detail</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                id &&
                <div>
                    <DetailAnime id={id}/>
                </div>
            }
        </AppLayout>
    )
}

export default Home
